<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.SHd6Y3y' shared service.

return $this->privates['.service_locator.SHd6Y3y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\PartenaireController::index' => ['privates', '.service_locator.eIEYWuf', 'get_ServiceLocator_EIEYWufService.php', true],
    'App\\Controller\\PartenaireController::new' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\PartenaireController::show' => ['privates', '.service_locator.iW_buO_', 'get_ServiceLocator_IWBuOService.php', true],
    'App\\Controller\\PartenaireController::update' => ['privates', '.service_locator.fDbIXxi', 'get_ServiceLocator_FDbIXxiService.php', true],
    'App\\Controller\\TransactionController::addDepot' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\WariController::register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\PartenaireController:index' => ['privates', '.service_locator.eIEYWuf', 'get_ServiceLocator_EIEYWufService.php', true],
    'App\\Controller\\PartenaireController:new' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\PartenaireController:show' => ['privates', '.service_locator.iW_buO_', 'get_ServiceLocator_IWBuOService.php', true],
    'App\\Controller\\PartenaireController:update' => ['privates', '.service_locator.fDbIXxi', 'get_ServiceLocator_FDbIXxiService.php', true],
    'App\\Controller\\TransactionController:addDepot' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\WariController:register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
], [
    'App\\Controller\\PartenaireController::index' => '?',
    'App\\Controller\\PartenaireController::new' => '?',
    'App\\Controller\\PartenaireController::show' => '?',
    'App\\Controller\\PartenaireController::update' => '?',
    'App\\Controller\\TransactionController::addDepot' => '?',
    'App\\Controller\\WariController::register' => '?',
    'App\\Controller\\PartenaireController:index' => '?',
    'App\\Controller\\PartenaireController:new' => '?',
    'App\\Controller\\PartenaireController:show' => '?',
    'App\\Controller\\PartenaireController:update' => '?',
    'App\\Controller\\TransactionController:addDepot' => '?',
    'App\\Controller\\WariController:register' => '?',
]);
