<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ9UNXmr\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ9UNXmr/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerZ9UNXmr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerZ9UNXmr\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerZ9UNXmr\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'Z9UNXmr',
    'container.build_id' => '0e6f1ebb',
    'container.build_time' => 1564518556,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ9UNXmr');
