<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXQGaNb8\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXQGaNb8/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerXQGaNb8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerXQGaNb8\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerXQGaNb8\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'XQGaNb8',
    'container.build_id' => '818e8a94',
    'container.build_time' => 1564508824,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXQGaNb8');
