<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYMfpFav\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYMfpFav/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerYMfpFav.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerYMfpFav\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerYMfpFav\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'YMfpFav',
    'container.build_id' => 'd8895b1b',
    'container.build_time' => 1564487881,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYMfpFav');
