<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFunigq2\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFunigq2/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFunigq2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFunigq2\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFunigq2\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Funigq2',
    'container.build_id' => 'e5f6df89',
    'container.build_time' => 1564486499,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFunigq2');
