<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIcxbI3S\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIcxbI3S/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIcxbI3S.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIcxbI3S\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIcxbI3S\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IcxbI3S',
    'container.build_id' => '8d0be70b',
    'container.build_time' => 1564484912,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIcxbI3S');
