<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCPiIvyl\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCPiIvyl/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCPiIvyl.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCPiIvyl\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCPiIvyl\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CPiIvyl',
    'container.build_id' => '58b51893',
    'container.build_time' => 1563915971,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCPiIvyl');
